export const metadata = {
  title: "Terms of Service | Luminous Will",
  description: "Terms of Service for Luminous Will video platform",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#e0e0e0] p-6 md:p-10 max-w-3xl mx-auto">
      <div className="mb-8">
        <a
          href="/"
          className="text-xs uppercase tracking-wider text-[#555] hover:text-[#E8A817] transition-colors"
        >
          &larr; Back
        </a>
      </div>

      <h1
        className="text-2xl font-bold mb-2"
        style={{ color: "#E8A817" }}
      >
        Terms of Service
      </h1>
      <p className="text-sm text-[#555] mb-8">
        Last updated: July 6, 2026
      </p>

      <div className="space-y-6 text-sm leading-relaxed text-[#aaa]">
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Luminous Will (&quot;the Service&quot;), available at
            luminous-will-web.vercel.app, you agree to be bound by these Terms of Service.
            If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">2. Description of Service</h2>
          <p>
            Luminous Will is an automated video generation and publishing platform. The Service
            allows users to generate motivational video content and publish it to third-party
            social media platforms including YouTube, TikTok, Instagram, and Facebook. The Service
            uses artificial intelligence to generate scripts, select stock footage, produce voiceovers,
            and assemble finished videos.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">3. User Accounts and Authentication</h2>
          <p>
            To use the publishing features, you must connect your social media accounts via OAuth
            authentication. By connecting an account, you authorize the Service to post content on
            your behalf to the connected platform. You may disconnect any platform at any time
            through the Settings page, which immediately revokes the Service&apos;s access to that platform.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">4. Content and Intellectual Property</h2>
          <p>
            Videos generated by the Service use third-party stock footage from Pexels and Pixabay
            under their respective free-use licenses, voiceovers generated via ElevenLabs, and
            AI-generated scripts via Google Gemini. You are responsible for reviewing all generated
            content before publishing. The Service provides a review and approval workflow for this purpose.
          </p>
          <p className="mt-2">
            You retain ownership of any custom topics or prompts you provide. You are solely
            responsible for the content you choose to publish to your social media accounts and
            for ensuring it complies with each platform&apos;s community guidelines and terms of service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">5. Third-Party Platform Terms</h2>
          <p>
            By using the Service to publish to third-party platforms, you agree to comply with
            their respective terms of service:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>YouTube Terms of Service (youtube.com/t/terms)</li>
            <li>TikTok Terms of Service (tiktok.com/legal/terms-of-service)</li>
            <li>Instagram Terms of Use (help.instagram.com/581066165581870)</li>
            <li>Facebook Terms of Service (facebook.com/terms.php)</li>
          </ul>
          <p className="mt-2">
            The Service accesses these platforms solely through their official APIs and within
            the scope of permissions you explicitly grant during the OAuth authorization process.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">6. Prohibited Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Use the Service to generate or publish content that violates any applicable law or platform policy</li>
            <li>Attempt to reverse-engineer, decompile, or extract source code from the Service</li>
            <li>Use the Service to spam, harass, or distribute misleading content</li>
            <li>Circumvent any security measures or access controls</li>
            <li>Resell or redistribute the Service without written permission</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">7. Auto-Posting and Scheduling</h2>
          <p>
            The Service offers automated scheduling and posting features. When auto-approve is
            enabled, generated videos may be posted to your connected accounts without manual
            review. You are responsible for managing this setting and for all content posted to
            your accounts, whether manually approved or auto-approved.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">8. Disclaimers</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
            uninterrupted or error-free operation. We are not responsible for any content removal,
            account suspension, or other actions taken by third-party platforms in response to
            content published through the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Luminous Will and its operators shall not be
            liable for any indirect, incidental, or consequential damages arising from your use
            of the Service, including but not limited to loss of revenue, data, or social media
            account standing.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">10. Termination</h2>
          <p>
            You may stop using the Service at any time by disconnecting all platform accounts via
            the Settings page. We reserve the right to suspend or terminate access to the Service
            at our discretion, with or without notice, for conduct that violates these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Changes will be posted on this page with
            an updated revision date. Continued use of the Service after changes constitutes
            acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">12. Contact</h2>
          <p>
            For questions about these Terms, contact us at:{" "}
            <a
              href="mailto:pmzo.mm08@gmail.com"
              className="text-[#E8A817] hover:underline"
            >
              pmzo.mm08@gmail.com
            </a>
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-[#1a1a1a] text-xs text-[#333] text-center">
        Luminous Will &middot; luminous-will-web.vercel.app
      </div>
    </div>
  );
}
